// react_monthy_11-13/src/components/Characters.jsx
import { useState,useEffect } from "react"

function Characters() {
  const[characters,setCharacters]=useState([]);
  const[page,setPage]=useState(2);

  useEffect(()=>{
    fetch(`https://rickandmortyapi.com/api/character?page=${page}`)
    .then(res=>res.json())
    .then(adat=>setCharacters(adat.results))
    .catch(err=>console.log(err));
  },[])

  return (
    <div>
      <h1 className="text-3x font-bold text-center text-sky-700">Szereplők:</h1>
      {
        characters.map((character)=>(<p key={character.id}>{character.name}</p>))
      }
    </div>
  )
}

export default Characters

// angular_morty/src/app/components/characters/characters.component.ts
import { Component, OnInit } from '@angular/core';
import { NgIf,NgFor } from '@angular/common';
import { CharacterComponent } from '../character/character.component';
import { Info } from '../../../types/info';
import { Character } from '../../../types/character';

@Component({
  selector: 'app-characters',
  standalone: true,
  imports: [NgIf,NgFor,CharacterComponent],
  templateUrl: './characters.component.html',
  styleUrl: './characters.component.css'
})
export class CharactersComponent implements OnInit  {

  ngOnInit(): void {
    this.getCharacters();
  }

  info:Info={} as Info;
  isLoading=false;
  results:Character[]=[];
  page=1;

  getCharacters(){
    this.isLoading=true;
    fetch(`https://rickandmortyapi.com/api/character?page=${this.page}`)
    .then(res=>res.json())
    .then(adat=>{
      this.info=adat.info;
      this.results=adat.results;
    })
    .catch(err=>alert(err))
    .finally(()=>this.isLoading=false);
  }

  tovabb(){
    console.log(this.page);
    if(this.page<this.info.pages){
      
      this.page+=1;
      this.getCharacters();
    }
  }

  vissza(){
    console.log(this.page);
    if(this.page>1){
      
      this.page-=1;
      this.getCharacters();
    }

  }

}

<h1 class="text-3xl font-bold text-center text-sky-700">Characters</h1>

<ng-container *ngIf="isLoading; else characterlist">
    <h2 class="text-2xl font-bold text-center text-sky-600">Betöltés...</h2>
</ng-container>


<ng-template #characterlist>
    <div class="join flex flex-row justify-center">
        <button (click)="vissza()" class="join-item btn">«</button>
        <button class="join-item btn">{{page}}</button>
        <button (click)="tovabb()" class="join-item btn">»</button>
      </div>
    <div class="flex flex-row flex-wrap items-center justify-center">
        <ng-container *ngFor="let result of results">
        
            <!--<p class="text-center">{{result.name}}</p>-->
            <app-character [result]="result" />
      
        </ng-container>
    </div>
    <div class="join flex flex-row justify-center">
        <button (click)="vissza()" class="join-item btn">«</button>
        <button class="join-item btn">{{page}}</button>
        <button (click)="tovabb()" class="join-item btn">»</button>
      </div>
</ng-template>
