// angular_morty/src/app/components/menu/menu.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './menu.component.html',
  styleUrl: './menu.component.css'
})
export class MenuComponent {

}

<div class="navbar bg-sky-200 shadow-sm">
    <div class="flex-1">
      <a routerLink="/" class="btn btn-ghost text-xl">Főoldal</a>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal px-1">
        <li><a routerLink="/characters">Characters</a></li>
        <li><a routerLink="/locations">Locations</a></li>
        <li><a routerLink="/episodes">Eposides</a></li>
        
      </ul>
    </div>
  </div>

// vue_proba/src/components/Menu.vue
<script setup>
import { RouterLink } from 'vue-router';
</script>

<template>
    <div class="navbar bg-slate-300 shadow-sm">
  <div class="flex-1">
    <RouterLink to="/" class="btn btn-ghost text-xl">Főoldal</RouterLink>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
        <li><RouterLink to="/typicode">Typicode</RouterLink></li>
        <li><RouterLink to="/randomusers">Randomusers</RouterLink></li>
      <li>
        <details>
          <summary>Parent</summary>
          <ul class="bg-base-100 rounded-t-none p-2">
            <li><a>Typicode</a></li>
            <li><a>Randomusers</a></li>
          </ul>
        </details>
      </li>
    </ul>
  </div>
</div>
    
</template>
