// angular/src/app/components/posts/posts.component.ts
import { Component, OnInit } from '@angular/core';
import { NgFor } from '@angular/common';

@Component({
  selector: 'app-posts',
  imports: [NgFor],
  templateUrl: './posts.component.html',
  styleUrl: './posts.component.css'
})
export class PostsComponent implements OnInit {
  ngOnInit(): void {
    this.getPosts();
  }

  posts:any=[];
  isLoading=false;

  getPosts(){
    this.isLoading=true;
    fetch('https://jsonplaceholder.typicode.com/posts')
    .then(res=>res.json())
    .then(posts=>this.posts=posts)
    .catch(err=>alert(err))
    .finally(()=>this.isLoading=false);


  }

}

<div class="flex flex-row flex-wrap">
    <ng-container *ngFor="let post of posts">
        <p>{{post.title}}</p>
    </ng-container>

</div>

// react_10-14/src/components/Posts.jsx
import { useState,useEffect } from "react";

function Posts() {
    //Kontroller
    const [posts,setPosts]=useState([]);

    useEffect(()=>{
       fetch('https://jsonplaceholder.typicode.com/posts/')
       .then(res=>res.json()) 
       .then(adatok=>setPosts(adatok))
       .catch(err=>console.log(err));
    },[]);

  return (
    <div>
        <h2>Posztok</h2>
        {
           posts.map((post,i)=>(<p key={i}>Id:{post.id}, Title:{post.title}</p>)) 
        }
    </div>
  )
}

export default Posts
