// react_monthy_11-13/src/components/Menu.jsx
import { Link } from "react-router-dom";

function Menu() {
  return (
    <div className="navbar bg-sky-400">
      <div className="flex-1">
        <Link to="/" className="btn btn-ghost text-xl">Rick and Morty API</Link>
      </div>
      <div className="flex-none">
        <ul className="menu menu-horizontal px-1">
          <li>
            <Link to="/characters">Szereplők</Link>
          </li>
          <li>
            <Link to="/episodes">Epizódok</Link>
          </li>
          <li>
            <Link to="/locations">Helyszínek</Link>
          </li>
          
        </ul>
      </div>
    </div>
  );
}

export default Menu;

// angular_morty/src/app/components/menu/menu.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './menu.component.html',
  styleUrl: './menu.component.css'
})
export class MenuComponent {

}

<div class="navbar bg-sky-200 shadow-sm">
    <div class="flex-1">
      <a routerLink="/" class="btn btn-ghost text-xl">Főoldal</a>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal px-1">
        <li><a routerLink="/characters">Characters</a></li>
        <li><a routerLink="/locations">Locations</a></li>
        <li><a routerLink="/episodes">Eposides</a></li>
        
      </ul>
    </div>
  </div>
