// vue_proba/src/components/Randomusers.vue
<script setup>
import {ref,onMounted} from 'vue';
const users=ref([]);
import Randomuser from './Randomuser.vue';

const fetchUsers=()=>{
    fetch('https://randomuser.me/api/?results=50')
    .then(res=>res.json())
    .then(adat=>users.value=adat.results)
    .catch(err=>alert(err));
}
onMounted(fetchUsers);
</script>

<template>
    <h1 class="text-3xl text-center">Users:{{ users.length }}</h1>
    <!--<div class="flex flex-row flex-wrap items-center justify-center">
        <div v-for="user in users">
            <Randomuser :user="user" />
        </div>
    </div>-->
    <div class="grid lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2">
        <div v-for="user in users">
            <Randomuser :user="user" />
        </div>
    </div>

</template>

// react_typescript/src/components/RandomUsers.tsx
import {useState,useEffect} from 'react';
import { RandUser } from '../types/RandUser';
import UserCard from './UserCard';



function RandomUsers() {
    const[users,setUsers]=useState(Array<RandUser>);
    useEffect(()=>{
        fetch("https://randomuser.me/api/?results=30")
        .then(res=>res.json())
        .then(adat=>setUsers(adat.results))
        .catch(err=>alert(err));
    },[])

  return (
    <div className="flex flex-row flex-wrap items-center justify-center">
        {
            users.map((user,i)=>(<UserCard key={i} user={user} />))
        }
    </div>
    
  )
}

export default RandomUsers
