// vue_proba/src/components/Typicode.vue
<script setup>
import { ref,onMounted } from 'vue';

const posts=ref([]);

const fetchPosts=()=>{
    fetch('https://jsonplaceholder.typicode.com/posts')
    .then(res=>res.json())
    .then(adat=>posts.value=adat)
    .catch(err=>alert(err));
}
onMounted(fetchPosts);
</script>

<template>
    <h1 class="text-center">Posts {{ posts.length }}</h1>
    <div v-for="post in posts">
        <p>{{ post.title }}</p>
    </div>
</template>

// react_typescript/src/components/Typicode.tsx
import { useState,useEffect } from "react";
import Post_ from "./Post_";

type Post={
    "userId":number,
    "id":number,
    "title":string,
    "body":string
}


function Typicode() {

    const[posts,setPosts]=useState(Array<Post>);
    useEffect(()=>{
        fetch('https://jsonplaceholder.typicode.com/posts')
        .then(res=>res.json())
        .then(adat=>setPosts(adat))
        .catch(err=>alert(err));
    },[])

  return (
    <div className="flex flex-row flex-wrap items-center justify-center">
        {
            //posts.map((post)=>(<p key={post.id}>Userid:{post.userId},{post.title}</p>))
            
            posts.map((post)=><Post_ key={post.id} post={post} />)
            
        }
    </div>
  )
}

export default Typicode
