// react_rick_and_morty/src/components/Character.jsx
function Character({character}) {
  return (
    <div className="card card-side bg-sky-200 shadow-xl m-5">
      <figure>
        <img
          src={character.image}
          alt="Movie"
        />
      </figure>
      <div className="card-body">
        <h2 className="card-title">{character.name}</h2>
        <p>Status: {character.status}</p>
        <p>Speci: {character.species}</p>
        <p>Gender: {character.gender}</p>
        <p>Origin: {character.origin.name}</p>
        <div className="card-actions justify-end">
          
        </div>
      </div>
    </div>
  );
}

export default Character;

// angular_morty/src/app/components/character/character.component.ts
import { Component, Input } from '@angular/core';
import { Character } from '../../../types/character';

@Component({
  selector: 'app-character',
  standalone: true,
  imports: [],
  templateUrl: './character.component.html',
  styleUrl: './character.component.css'
})
export class CharacterComponent {

  @Input()
  result:Character={} as Character;

}

<div class="m-2 w-96 card card-side bg-sky-200 shadow-sm">
    <figure>
      <img
        src={{result.image}}
        alt="character" />
    </figure>
    <div class="card-body">
      <h2 class="card-title">{{result.name}}</h2>
      <p>{{result.status}}</p>
      <p>{{result.species}}</p>
      <p>{{result.gender}}</p>
      <div class="card-actions justify-end">
        
      </div>
    </div>
  </div>
