// vue_proba/src/components/Menu.vue
<script setup>
import { RouterLink } from 'vue-router';
</script>

<template>
    <div class="navbar bg-slate-300 shadow-sm">
  <div class="flex-1">
    <RouterLink to="/" class="btn btn-ghost text-xl">Főoldal</RouterLink>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
        <li><RouterLink to="/typicode">Typicode</RouterLink></li>
        <li><RouterLink to="/randomusers">Randomusers</RouterLink></li>
      <li>
        <details>
          <summary>Parent</summary>
          <ul class="bg-base-100 rounded-t-none p-2">
            <li><a>Typicode</a></li>
            <li><a>Randomusers</a></li>
          </ul>
        </details>
      </li>
    </ul>
  </div>
</div>
    
</template>

// autok_12-11/src/components/Menu.jsx
import { Link } from "react-router-dom";

function Menu() {
  return (
    <div className="navbar bg-red-200">
      <div className="flex-1">
        <Link to="/" className="btn btn-ghost text-xl">Autók</Link>
      </div>
      <div className="flex-none">
        <ul className="menu menu-horizontal px-1">
          <li>
            <Link to="/autolista">Autó lista</Link>
          </li>
          <li>
            <Link to="/ujauto" >Új autó felvitele</Link>
          </li>
        
        </ul>
      </div>
    </div>
  );
}

export default Menu;
